### ISSUE TITLE
Podfile  文件内容是否不完整? pod install的时候会报错。

### ISSUE THREAD

**Issue by JimmyLee05** [herrkaefer/CaseAssistant#1]
<img width="571" alt="2017-10-12 11 09 42" src="https://user-images.githubusercontent.com/13815229/31503788-2832056e-afa3-11e7-997e-842bd8d831fa.png">
<img width="745" alt="2017-10-12 11 11 56" src="https://user-images.githubusercontent.com/13815229/31503795-2bd43d22-afa3-11e7-837f-6d09ec9720ce.png">
<img width="463" alt="2017-10-12 11 12 40" src="https://user-images.githubusercontent.com/13815229/31503803-309e25fc-afa3-11e7-8b49-ef482e9998f0.png">

**Comment by herrkaefer** [comment]
@JimmyLee05 删掉`podfile.lock`再试试

**Comment by JimmyLee05** [comment]
删掉 podfile.lock后 pod install还是报上面那个错，我把 Profile文件里的 target `CaseAssistantTests` do end 这一段删除后可以正常安装第三方库。但是在编译的时候报了ObjectiveCBridgingHeader.h No such file or directory 的问题，看了文件目录没找到相关文件，google了下后没能解决。。。

**Comment by JimmyLee05** [comment]
@herrkaefer 问题解决了，这个项目之前用OC写过，所以项目里有相关的设置，清空就好了

![2017-10-26 2 40 11](https://user-images.githubusercontent.com/13815229/32038286-b535e774-ba5b-11e7-8750-9bc73dd90cff.png)
